# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Undone my breakdown
email: dhavirus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I kinda dropped out a PhD program in KyotoU, worked my way hard to land a job in a small local pharmaceutical compamy, and currently trying to figure things out. 

url: "https://dhanhdjs.github.io/labnote" # the base hostname & protocol for your site
twitter_username: dhanhdjs
github_username:  dhanhdjs

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
